# CommaFeed RSS Reader Values (using bjw-s app-template)
controllers:
  main:
    replicas: 1
    containers:
      main:
        image:
          repository: athou/commafeed
          tag: latest
        env:
          TZ: America/New_York
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m

service:
  main:
    ports:
      http:
        port: 8082

persistence:
  config:
    enabled: true
    size: 1Gi
    globalMounts:
      - path: /commafeed/data

ingress:
  main:
    enabled: false  # We'll use Istio Gateway

# CommaFeed configuration
configMaps:
  config:
    enabled: true
    data:
      config.yml: |
        app:
          publicUrl: http://commafeed.dev.cluster.local
          allowRegistrations: true
          createDemoAccount: true
          
        database:
          # Will use H2 embedded database for simplicity in dev
          driverClass: org.h2.Driver
          url: jdbc:h2:./data/commafeed
          user: sa
          password: ""
          
        cache:
          # Redis cache configuration
          provider: redis
          redis:
            host: redis-master.cache.svc.cluster.local
            port: 6379
            password: redis123