# Updated PostgreSQL with Environment-Specific Database Names
auth:
  postgresPassword: postgres123
  database: postgres

primary:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  
  persistence:
    enabled: true
    size: 20Gi

  # Initialize databases with environment prefix
  initdb:
    scripts:
      01-create-databases.sql: |
        CREATE DATABASE dev_wallabag;
        CREATE USER dev_wallabag WITH PASSWORD 'wallabag123';
        GRANT ALL PRIVILEGES ON DATABASE dev_wallabag TO dev_wallabag;
        
        CREATE DATABASE dev_n8n;
        CREATE USER dev_n8n WITH PASSWORD 'n8n123';
        GRANT ALL PRIVILEGES ON DATABASE dev_n8n TO dev_n8n;
        
        CREATE DATABASE dev_linkding;
        CREATE USER dev_linkding WITH PASSWORD 'linkding123';
        GRANT ALL PRIVILEGES ON DATABASE dev_linkding TO dev_linkding;

metrics:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m