# n8n Workflow Automation Values
replicaCount: 1

image:
  repository: n8nio/n8n
  tag: latest

service:
  type: ClusterIP
  port: 5678

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce

env:
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - name: N8N_BASIC_AUTH_USER
    value: "admin"
  - name: N8N_BASIC_AUTH_PASSWORD
    value: "admin123"
  - name: N8N_HOST
    value: "n8n.dev.cluster.local"
  - name: N8N_PORT
    value: "5678"
  - name: N8N_PROTOCOL
    value: "http"
  - name: WEBHOOK_URL
    value: "http://n8n.dev.cluster.local"
  - name: GENERIC_TIMEZONE
    value: "America/New_York"
  - name: N8N_LOG_LEVEL
    value: "info"
  - name: N8N_DIAGNOSTICS_ENABLED
    value: "false"
  - name: N8N_PERSONALIZATION_ENABLED
    value: "false"
  - name: N8N_VERSION_NOTIFICATIONS_ENABLED
    value: "false"

# Database configuration (will use external PostgreSQL)
database:
  enabled: false

ingress:
  enabled: false  # We'll use Istio Gateway