apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-config
  namespace: bookmarks
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkding-secret
    creationPolicy: Owner
  data:
  - secretKey: superuser-name
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/linkding
      metadataPolicy: None
      property: superuser_name
  - secretKey: superuser-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/linkding
      metadataPolicy: None
      property: superuser_password
  - secretKey: db-username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/linkding
      metadataPolicy: None
      property: db_username
  - secretKey: db-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/linkding
      metadataPolicy: None
      property: db_password