apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-config
  namespace: automation
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-secret
    creationPolicy: Owner
  data:
  - secretKey: basic-auth-user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/n8n
      metadataPolicy: None
      property: basic_auth_user
  - secretKey: basic-auth-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/n8n
      metadataPolicy: None
      property: basic_auth_password
  - secretKey: db-username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/n8n
      metadataPolicy: None
      property: db_username
  - secretKey: db-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/n8n
      metadataPolicy: None
      property: db_password