apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-database
  namespace: databases
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: database-secret
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: postgres_password
  - secretKey: postgres-username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: postgres_username
  - secretKey: PGHOST
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: PGHOST
  - secretKey: PGPORT
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: PGPORT
  - secretKey: dev-wallabag-username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: dev_wallabag_username
  - secretKey: dev-wallabag-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: dev_wallabag_password
  - secretKey: dev-n8n-username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: dev_n8n_username
  - secretKey: dev-n8n-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: dev_n8n_password
  - secretKey: dev-linkding-username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: dev_linkding_username
  - secretKey: dev-linkding-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/postgresql
      metadataPolicy: None
      property: dev_linkding_password