apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-database
  namespace: cache
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
  - secretKey: redis-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/redis
      metadataPolicy: None
      property: password