apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-config
  namespace: reading
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wallabag-secret
    creationPolicy: Owner
  data:
  - secretKey: db-username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/wallabag
      metadataPolicy: None
      property: db_username
  - secretKey: db-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/wallabag
      metadataPolicy: None
      property: db_password
  - secretKey: redis-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/redis
      metadataPolicy: None
      property: password