apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ArgoCD will apply this kustomization.yaml file for applications

helmCharts:
# Homepage Dashboard
- name: homepage
  repo: https://jameswynn.github.io/helm-charts
  version: 1.2.3
  releaseName: homepage
  namespace: dashboard
  valuesFile: ../values/values-homepage.yaml

# n8n Workflow Automation
- name: n8n
  repo: https://8gears.container-registry.com/chartrepo/library
  version: 0.21.0
  releaseName: n8n
  namespace: automation
  valuesFile: ../values/values-n8n.yaml

# Wallabag Read-later Service
- name: wallabag
  repo: https://charts.truecharts.org
  version: 8.0.15
  releaseName: wallabag
  namespace: reading
  valuesFile: ../values/values-wallabag.yaml

# CommaFeed RSS Reader - Using generic app chart
- name: commafeed
  repo: https://bjw-s.github.io/helm-charts
  version: 2.4.0
  releaseName: commafeed
  namespace: rss
  valuesFile: ../values/values-commafeed.yaml

# Linkding Bookmark Manager - Using generic app chart
- name: linkding
  repo: https://bjw-s.github.io/helm-charts
  version: 2.4.0
  releaseName: linkding
  namespace: bookmarks
  valuesFile: ../values/values-linkding.yaml

# PostgreSQL for applications that need it
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: 13.2.24
  releaseName: postgresql
  namespace: databases
  valuesFile: ../values/values-postgresql.yaml

# Redis for caching
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 18.4.0
  releaseName: redis
  namespace: cache
  valuesFile: ../values/values-redis.yaml

resources:
  - namespaces.yaml
  - istio-virtual-services.yaml

commonLabels:
  environment: dev
  managed-by: argocd
  component: applications